### ISSUE TITLE
Unused and invalid `app.run`

### ISSUE THREAD

**Issue by riemanli** [world-federation-of-advertisers/cardinality_estimation_evaluation_framework#126]
https://github.com/world-federation-of-advertisers/cardinality_estimation_evaluation_framework/blob/732117efd307230156376e88f4d2ab3bb6b5df97/src/common/noisers.py#L229-L235

Hi. Do we need the code shown in the snippet above? `main` doesn't do anything but check number of command-line arguments. Plus, `absl.app` is not imported in this module, which causes problems.

**Comment by jiayu-google** [comment]
Agreed, unnecessary to me.

**Comment by riemanli** [comment]
https://github.com/world-federation-of-advertisers/cardinality_estimation_evaluation_framework/blob/732117efd307230156376e88f4d2ab3bb6b5df97/src/estimators/estimator_noisers.py#L124-L130

Found one more file has the same issue. Removed it in the same PR #127.
